### ISSUE TITLE
Could not process authentication token for user xyz. Did you mess up your username/password?

### ISSUE THREAD

**Issue by bashaasun** [Appdynamics/list-nodes#1]
I am keep getting the below error message. I tried the following command. 

$. ./list-nodes.py -p 8181 -s xyz.domain.com admin password 
Could not process authentication token for user xyz. Did you mess up your username/password?
$

**Comment by dlefebvreappd** [comment]
I should make the instructions more complete.  The username must be in the format:
<username>@<account>

For example, if it is an on-prem controller, then most likely the account is "customer1".  If the username is bob, then the complete username should be:
bob@customer1

The username can also be in the form of an e-mail address.  This can add some confusion.  If, for the same controller as in the previous example, the username is bob@someplace.com, the complete username should be:
bob@someplace.com@customer1

If it is a multi-tenant controller or a SaaS controller, the account name is usually the first part of the host name: the account name for someplace.saas.appdynamics.com is most likely someplace.  So the complete username should be:
bob@someplace.com@someplace
